import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { test, expect, type Page } from '@playwright/test';
// Type-only: erased at compile time, so it never becomes a runtime import of
// `examples/src/bench.ts` (which imports `phaser` as a VALUE — same crash render.spec.ts's
// helpers.ts documents in full for scene.ts). This pulls in `BenchResults`/`IsoBenchHook` and
// the `declare global { interface Window { __bench?: ... } } ` augmentation for free.
import type { BenchResults, IsoBenchHook } from '../src/bench';

const here = path.dirname(fileURLToPath(import.meta.url));
const ARTIFACTS = path.join(here, 'artifacts');

// Runtime CONSTANTS still have to be duplicated (types don't, see the import above): these are
// values, and importing a value from bench.ts would force Node to evaluate the whole module,
// including its `new Phaser.Game(...)` side effect. Copied 1:1 from examples/src/bench.ts.
const DEFAULT_ENTITY_COUNT = 500;
const WARMUP_FRAMES = 60;
const MEASURE_FRAMES = 300;
const P95_THRESHOLD_MS = 16.6;
const RUNS = 3;

/**
 * Fix round 2, Item 2: the standing rule this project adopted after fix round 1 — a floor can
 * never again be silently read as a cost — has to be an assertion, not just the `console.log`
 * comparison below. The report's own 9-run data puts the real ratio (500-entity mean vs.
 * 0-entity control mean) somewhere in a 2.5-5x band, not a flat constant (see the report's Item
 * 1 correction for why it is a band, not a point estimate). `2` is comfortably BELOW that band's
 * low end, with margin to spare — the point of this assertion is to fire when the
 * entity-dependent signal disappears entirely (e.g. a future metric that flatlines regardless of
 * entity count, fix round 1's own original defect), not to pin the ratio precisely.
 */
const NULL_HYPOTHESIS_MULTIPLIER = 2;

/**
 * The median frame period README.md's "Performance" section and SKILL.md gotcha 4 both quote.
 * Measured 8.3000ms in six of six runs on 2026-07-30 with the benchmark run ALONE — it is
 * 1/120s, the cadence headless Chromium hands out, which is why the documents phrase the claim
 * as "held the browser's own frame cadence" rather than as a cost. Kept as a literal rather than
 * derived from P95_THRESHOLD_MS so that changing the published figure is a deliberate edit here,
 * in the place whose warning names the two documents to update.
 */
const PUBLISHED_FRAME_PERIOD_MEDIAN_MS = 8.3;

/**
 * How far the measured median may drift from the published figure before this suite says so.
 * It drives a console.warn, NOT an assertion — see the long comment at the comparison below for
 * the measurement that ruled an assertion out (10.700ms in-suite vs 8.300ms standalone, same
 * commit, same machine).
 */
const PUBLISHED_FIGURE_TOLERANCE = 0.05;

// The published sentence is "an 8.3 ms median frame period, at least 2x inside the 16.6 ms /
// 60 fps budget". That "2x" is a RELATIONSHIP between the two constants above, so editing one
// without the other silently makes the documents' arithmetic false while every assertion below
// stays green. Same guard style as the baseline.entityCount check further down.
if (PUBLISHED_FRAME_PERIOD_MEDIAN_MS * 2 > P95_THRESHOLD_MS) {
    throw new Error(
        `README.md claims the ${PUBLISHED_FRAME_PERIOD_MEDIAN_MS}ms median frame period is at least `
        + `2x inside the ${P95_THRESHOLD_MS}ms budget, and these two constants no longer support that `
        + 'sentence — fix the constants or fix the sentence.'
    );
}

/**
 * Fix round 1: the CI-enforced regression gate for `frameWorkTime`, curated and committed
 * deliberately — NOT regenerated by every run, which is exactly what would let the gate drift
 * to match whatever the current code happens to do. See `examples/e2e/artifacts/bench-baseline.json`.
 */
interface BenchBaseline {
    readonly recordedOn: string;
    readonly machine: string;
    readonly entityCount: number;
    readonly frameWorkTimeP95Ms: number;
    readonly toleranceMultiplier: number;
}

const baseline: BenchBaseline = JSON.parse(
    fs.readFileSync(path.join(ARTIFACTS, 'bench-baseline.json'), 'utf8')
) as BenchBaseline;

// Fix round 2: a baseline file hand-edited to a different entityCount (e.g. while updating it
// for a different scene size) would otherwise be silently applied to the 500-entity gate below —
// the mismatch would never surface as anything other than a p95 comparison that quietly means
// something else. Fail loudly instead.
if (baseline.entityCount !== DEFAULT_ENTITY_COUNT) {
    throw new Error(
        `bench-baseline.json was recorded for entityCount=${baseline.entityCount}, `
        + `but this suite's main runs use DEFAULT_ENTITY_COUNT=${DEFAULT_ENTITY_COUNT} — `
        + 'update the baseline (or this constant) so they agree before trusting the gate below.'
    );
}

async function runOnce(page: Page, entityCount: number): Promise<{ results: BenchResults; rendererInfo: string | null }> {
    // A fresh navigation per run — no JIT warm-up, GC state, or GL context carries over from a
    // previous run, so runs at the same entityCount are independent samples of the same fixed
    // workload (fixed PRNG seed inside bench.ts), not points on one continuously-warming curve.
    await page.goto(`/bench.html?entities=${entityCount}`);
    await page.waitForFunction(() => Boolean(window.__bench));

    // WARMUP_FRAMES + MEASURE_FRAMES frames at a plausibly-slow 20fps would still be well
    // under 30s; this generous ceiling exists for slow/loaded machines, not because the run is
    // expected to take anywhere near it.
    await page.waitForFunction(() => window.__bench?.done === true, undefined, { timeout: 60_000 });

    const hook = await page.evaluate(() => window.__bench as IsoBenchHook);
    if (!hook.results) throw new Error('bench finished but produced no results');
    return { results: hook.results, rendererInfo: hook.rendererInfo };
}

function logRun(label: string, run: { results: BenchResults; rendererInfo: string | null }): void {
    console.log(`[bench ${label}] renderer=${run.rendererInfo ?? '(none)'}`);
    console.log(JSON.stringify(run.results, null, 2));
}

test.describe('Task 13 — the 500-entity benchmark gate @bench', () => {
    test.setTimeout(120_000);

    test(`measures the four metrics across ${RUNS} runs, plus a ${RUNS}-run null-hypothesis control`, async ({ page }) => {
        // --- The scene: DEFAULT_ENTITY_COUNT (500) active entities. ---
        const mainRuns: Array<{ results: BenchResults; rendererInfo: string | null }> = [];

        for (let i = 0; i < RUNS; i += 1) {
            const run = await runOnce(page, DEFAULT_ENTITY_COUNT);
            mainRuns.push(run);
            logRun(`500-entity run ${i + 1}/${RUNS}`, run);

            expect(run.results.entityCount).toBe(DEFAULT_ENTITY_COUNT);
            expect(run.results.measuredFrames).toBe(MEASURE_FRAMES);
            expect(run.results.warmupFrames).toBe(WARMUP_FRAMES);

            // Fix round 1 (d): what this invariant actually establishes — 500 setDepth() calls
            // per frame coalesce into exactly ONE actual sort, never zero (something did move)
            // and never more (the flag is consumed and cleared the instant `depthSort()` runs).
            // It does NOT, on its own, prove "setDepth is never called after the sort": a
            // post-sort setDepth this frame would only re-raise `sortChildrenFlag` for the NEXT
            // frame's sort, not trigger a second one this frame — and with input disabled here,
            // the only OTHER call site that could ever produce a same-frame double sort
            // (`InputPlugin#sortDropZones`, `src/input/InputPlugin.js` around line 2910, reached
            // only via >=2 active drop zones) is structurally unreachable in this scene. So this
            // scene's design, chosen for cost-isolation reasons, also removes the only mechanism
            // that could have made this specific counter fail — the invariant holding here is
            // real evidence the coalescing mechanism works, not evidence against a hazard this
            // scene was never able to exercise in the first place.
            expect(run.results.depthSortPerFrame.min, `run ${i + 1}: depthSort min`).toBe(1);
            expect(run.results.depthSortPerFrame.max, `run ${i + 1}: depthSort max`).toBe(1);
            expect(run.results.depthSortPerFrame.mean, `run ${i + 1}: depthSort mean`).toBe(1);

            // Fix round 1 (b): pinned to the exact values nine independent runs (three of them
            // an external reviewer's own re-run) reproduced bit-for-bit — the simulation is
            // fully deterministic given the fixed PRNG seed and the frame-indexed (not
            // delta-time) movement model, so `drawnMean < total` alone (previously the only
            // check here) would still pass at 499/500 and catch nothing. Any change to the
            // projection, `cullBounds`, or the camera/follow path should turn this red.
            expect(run.results.culling.drawnMin, `run ${i + 1}: culling drawnMin`).toBe(23);
            expect(run.results.culling.drawnMax, `run ${i + 1}: culling drawnMax`).toBe(59);
            expect(run.results.culling.drawnMean, `run ${i + 1}: culling drawnMean`).toBeCloseTo(44.8, 4);
            expect(run.results.culling.total).toBe(DEFAULT_ENTITY_COUNT);

            // Fix round 1 (a), sensitivity corrected in fix round 2: the actual CI regression
            // gate, against a curated, committed baseline — NOT the 16.6ms/60fps aspirational
            // number (that comparison is printed below and recorded in the report, but
            // deliberately never asserted: a build that goes red because reality is slower than
            // an aspirational target would pressure someone into shrinking the scene, which this
            // task exists to refuse to do). What this gate actually catches, worked out from
            // this benchmark's own numbers (full derivation in bench-baseline.json's `_purpose`
            // and the report's fix-(a) section): roughly an 8-12x blowup in the
            // ENTITY-ATTRIBUTABLE portion of frameWorkTime (~0.15-0.20ms today). It is a
            // catastrophe-catcher, not a fine-grained regression detector — a 10x `place()`
            // slowdown or a broken depthSort coalescing (caught instead by the
            // depthSort===1 assertion above) would NOT trip it at today's numbers.
            expect(
                run.results.frameWorkTime.p95,
                `run ${i + 1}: frameWorkTime.p95 vs baseline ${baseline.frameWorkTimeP95Ms}ms x ${baseline.toleranceMultiplier}`
            ).toBeLessThan(baseline.frameWorkTimeP95Ms * baseline.toleranceMultiplier);
        }

        // --- The null-hypothesis control: the SAME page, SAME instrumentation, 0 entities. ---
        const controlRuns: Array<{ results: BenchResults; rendererInfo: string | null }> = [];

        for (let i = 0; i < RUNS; i += 1) {
            const run = await runOnce(page, 0);
            controlRuns.push(run);
            logRun(`0-entity control ${i + 1}/${RUNS}`, run);

            expect(run.results.entityCount).toBe(0);
            expect(run.results.culling.total).toBe(0);

            // With nothing ever calling setCell()/place(), setDepth() is never called, so
            // sortChildrenFlag is never raised — depthSort must read exactly 0, not 1. A
            // different invariant from the 500-entity scene, for the same architectural reason.
            expect(run.results.depthSortPerFrame.min, `control ${i + 1}: depthSort min`).toBe(0);
            expect(run.results.depthSortPerFrame.max, `control ${i + 1}: depthSort max`).toBe(0);
            expect(run.results.depthSortPerFrame.mean, `control ${i + 1}: depthSort mean`).toBe(0);
        }

        // --- The point of the control: prove framePeriod is a floor, frameWorkTime is not. ---
        for (const [i, run] of mainRuns.entries()) {
            const control = controlRuns[i];
            console.log(
                `[bench comparison ${i + 1}/${RUNS}] `
                + `framePeriod 500=${run.results.framePeriod.median.toFixed(3)}ms `
                + `0=${control.results.framePeriod.median.toFixed(3)}ms `
                + `(expected to be close — that is the floor) | `
                + `frameWorkTime 500=${run.results.frameWorkTime.mean.toFixed(3)}ms `
                + `0=${control.results.frameWorkTime.mean.toFixed(3)}ms `
                + `(expected to differ — that is the actual cost)`
            );

            // Post-plan minor: `framePeriod` was the LAST metric here that only printed, and it
            // is the one the published promise is made of — README.md's "Performance" section
            // and SKILL.md gotcha 4 both quote "an 8.3 ms median frame period, at least 2x
            // inside the 16.6 ms / 60 fps budget". A number nobody asserts is free to drift away
            // from the documents that quote it.
            //
            // WHAT IS ASSERTED, and why it is the budget rather than the control. The first
            // draft of this compared the 500-entity median against the 0-entity control's, on
            // the reasoning that "held the browser's cadence" is a relative claim. That draft
            // went RED on a healthy build the second time it ran, and the numbers say why:
            //
            //   `pnpm e2e --grep @bench` (benchmark alone):  500 = 8.300ms   control = 8.300ms
            //   `pnpm e2e` (whole suite):                    500 = 10.700ms  control = 8.300ms
            //
            // Same commit, same machine, minutes apart. The 500-entity runs execute FIRST in
            // this test, immediately after the ten other browser tests; the controls execute
            // afterwards, once the machine has settled. So the relative form measures that
            // ordering at least as much as it measures the plugin — RELEASING.md section 3
            // already documents the same effect (10.6ms on a busy machine, 8.3 idle, no code
            // change). A gate that reds on a perfect package is worse than no gate.
            //
            // The durable, machine-independent half of the claim is "inside the 60 fps budget",
            // and that is what this asserts. 8.3 and 10.7 both pass; a genuine cadence collapse
            // does not.
            //
            // KNOWN BLIND SPOT, stated so nobody mistakes this for a sensitive gate: framePeriod
            // is quantized to the browser's cadence, so per-frame cost can grow from today's
            // ~0.2ms to several ms — a 40x regression — with this still green, because the
            // frames keep landing inside the interval. `frameWorkTime` below is the sensitive
            // metric; this one guards the shape of the published claim.
            expect(
                run.results.framePeriod.median,
                `run ${i + 1}: framePeriod.median (${run.results.framePeriod.median}ms) is outside the `
                + `${P95_THRESHOLD_MS}ms / 60 fps budget that README.md and SKILL.md gotcha 4 both claim. `
                + 'Before reading this as a regression: re-run on an idle machine with `pnpm e2e --grep '
                + '@bench`, because a loaded one inflates this metric on its own (RELEASING.md section 3)'
            ).toBeLessThanOrEqual(P95_THRESHOLD_MS);

            // The absolute figure the documents print CANNOT be asserted, for the reason above:
            // any comparison against 8.3ms is a machine-and-invocation detector, not a code
            // gate. It is not therefore ignorable — it is routed to the human step that can
            // actually judge it, RELEASING.md's "re-measure on an idle machine" checklist item,
            // and this warning is what makes that step fire instead of being remembered.
            const scarto = Math.abs(run.results.framePeriod.median - PUBLISHED_FRAME_PERIOD_MEDIAN_MS);
            if (scarto > PUBLISHED_FRAME_PERIOD_MEDIAN_MS * PUBLISHED_FIGURE_TOLERANCE) {
                console.warn(
                    `[bench run ${i + 1}/${RUNS}] framePeriod.median=${run.results.framePeriod.median.toFixed(3)}ms `
                    + `vs the ${PUBLISHED_FRAME_PERIOD_MEDIAN_MS}ms quoted in README.md and SKILL.md gotcha 4. `
                    + 'If you are about to publish, re-measure on an idle machine and update BOTH documents '
                    + '(RELEASING.md section 3). If you are not, this is almost certainly machine load.'
                );
            }

            // Fix round 2, Item 2: this was a console.log and nothing else — the "floor can
            // never again be read as a cost" rule shipped as a print statement, so a future
            // frameWorkTime that flatlined at the control's ~0.06-0.07ms regardless of entity
            // count would pass this whole suite. Now it can't: the entity-attributable signal
            // must clear the control by a real margin, not just print alongside it.
            expect(
                run.results.frameWorkTime.mean,
                `run ${i + 1}: frameWorkTime.mean (${run.results.frameWorkTime.mean}ms) must clear `
                + `the null-hypothesis control (${control.results.frameWorkTime.mean}ms) by at `
                + `least ${NULL_HYPOTHESIS_MULTIPLIER}x — if it doesn't, the entity-count signal `
                + 'has disappeared, which is exactly the failure fix round 1 exists to catch'
            ).toBeGreaterThan(control.results.frameWorkTime.mean * NULL_HYPOTHESIS_MULTIPLIER);

            const verdict = run.results.frameWorkTime.p95 < P95_THRESHOLD_MS ? 'PASS' : 'MISS';
            console.log(
                `[bench run ${i + 1}/${RUNS}] frameWorkTime.p95=${run.results.frameWorkTime.p95.toFixed(3)}ms `
                + `vs aspirational threshold=${P95_THRESHOLD_MS}ms: ${verdict} (informational only, not asserted)`
            );
        }

        fs.mkdirSync(ARTIFACTS, { recursive: true });
        fs.writeFileSync(
            path.join(ARTIFACTS, 'bench-results.json'),
            `${JSON.stringify({ defaultEntityCount: DEFAULT_ENTITY_COUNT, p95ThresholdMs: P95_THRESHOLD_MS, mainRuns, controlRuns }, null, 2)}\n`
        );
    });
});
