import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { test, expect, type Page } from '@playwright/test';
// Type-only: erased at compile time, so it never becomes a runtime import of
// `examples/src/bench.ts` (which imports `phaser` as a VALUE — same crash render.spec.ts's
// helpers.ts documents in full for scene.ts). This pulls in `BenchResults`/`IsoBenchHook` and
// the `declare global { interface Window { __bench?: ... } } ` augmentation for free.
import type { BenchResults, IsoBenchHook } from '../src/bench';

const here = path.dirname(fileURLToPath(import.meta.url));
const ARTIFACTS = path.join(here, 'artifacts');

// Runtime CONSTANTS still have to be duplicated (types don't, see the import above): these are
// values, and importing a value from bench.ts would force Node to evaluate the whole module,
// including its `new Phaser.Game(...)` side effect. Copied 1:1 from examples/src/bench.ts.
const DEFAULT_ENTITY_COUNT = 500;
const WARMUP_FRAMES = 60;
const MEASURE_FRAMES = 300;
const P95_THRESHOLD_MS = 16.6;
const RUNS = 3;

/**
 * Fix round 2, Item 2: the standing rule this project adopted after fix round 1 — a floor can
 * never again be silently read as a cost — has to be an assertion, not just the `console.log`
 * comparison below. The report's own 9-run data puts the real ratio (500-entity mean vs.
 * 0-entity control mean) somewhere in a 2.5-5x band, not a flat constant (see the report's Item
 * 1 correction for why it is a band, not a point estimate). `2` is comfortably BELOW that band's
 * low end, with margin to spare — the point of this assertion is to fire when the
 * entity-dependent signal disappears entirely (e.g. a future metric that flatlines regardless of
 * entity count, fix round 1's own original defect), not to pin the ratio precisely.
 */
const NULL_HYPOTHESIS_MULTIPLIER = 2;

/**
 * Fix round 1: the CI-enforced regression gate for `frameWorkTime`, curated and committed
 * deliberately — NOT regenerated by every run, which is exactly what would let the gate drift
 * to match whatever the current code happens to do. See `examples/e2e/artifacts/bench-baseline.json`.
 */
interface BenchBaseline {
    readonly recordedOn: string;
    readonly machine: string;
    readonly entityCount: number;
    readonly frameWorkTimeP95Ms: number;
    readonly toleranceMultiplier: number;
}

const baseline: BenchBaseline = JSON.parse(
    fs.readFileSync(path.join(ARTIFACTS, 'bench-baseline.json'), 'utf8')
) as BenchBaseline;

// Fix round 2: a baseline file hand-edited to a different entityCount (e.g. while updating it
// for a different scene size) would otherwise be silently applied to the 500-entity gate below —
// the mismatch would never surface as anything other than a p95 comparison that quietly means
// something else. Fail loudly instead.
if (baseline.entityCount !== DEFAULT_ENTITY_COUNT) {
    throw new Error(
        `bench-baseline.json was recorded for entityCount=${baseline.entityCount}, `
        + `but this suite's main runs use DEFAULT_ENTITY_COUNT=${DEFAULT_ENTITY_COUNT} — `
        + 'update the baseline (or this constant) so they agree before trusting the gate below.'
    );
}

async function runOnce(page: Page, entityCount: number): Promise<{ results: BenchResults; rendererInfo: string | null }> {
    // A fresh navigation per run — no JIT warm-up, GC state, or GL context carries over from a
    // previous run, so runs at the same entityCount are independent samples of the same fixed
    // workload (fixed PRNG seed inside bench.ts), not points on one continuously-warming curve.
    await page.goto(`/bench.html?entities=${entityCount}`);
    await page.waitForFunction(() => Boolean(window.__bench));

    // WARMUP_FRAMES + MEASURE_FRAMES frames at a plausibly-slow 20fps would still be well
    // under 30s; this generous ceiling exists for slow/loaded machines, not because the run is
    // expected to take anywhere near it.
    await page.waitForFunction(() => window.__bench?.done === true, undefined, { timeout: 60_000 });

    const hook = await page.evaluate(() => window.__bench as IsoBenchHook);
    if (!hook.results) throw new Error('bench finished but produced no results');
    return { results: hook.results, rendererInfo: hook.rendererInfo };
}

function logRun(label: string, run: { results: BenchResults; rendererInfo: string | null }): void {
    console.log(`[bench ${label}] renderer=${run.rendererInfo ?? '(none)'}`);
    console.log(JSON.stringify(run.results, null, 2));
}

test.describe('Task 13 — the 500-entity benchmark gate @bench', () => {
    test.setTimeout(120_000);

    test(`measures the four metrics across ${RUNS} runs, plus a ${RUNS}-run null-hypothesis control`, async ({ page }) => {
        // --- The scene: DEFAULT_ENTITY_COUNT (500) active entities. ---
        const mainRuns: Array<{ results: BenchResults; rendererInfo: string | null }> = [];

        for (let i = 0; i < RUNS; i += 1) {
            const run = await runOnce(page, DEFAULT_ENTITY_COUNT);
            mainRuns.push(run);
            logRun(`500-entity run ${i + 1}/${RUNS}`, run);

            expect(run.results.entityCount).toBe(DEFAULT_ENTITY_COUNT);
            expect(run.results.measuredFrames).toBe(MEASURE_FRAMES);
            expect(run.results.warmupFrames).toBe(WARMUP_FRAMES);

            // Fix round 1 (d): what this invariant actually establishes — 500 setDepth() calls
            // per frame coalesce into exactly ONE actual sort, never zero (something did move)
            // and never more (the flag is consumed and cleared the instant `depthSort()` runs).
            // It does NOT, on its own, prove "setDepth is never called after the sort": a
            // post-sort setDepth this frame would only re-raise `sortChildrenFlag` for the NEXT
            // frame's sort, not trigger a second one this frame — and with input disabled here,
            // the only OTHER call site that could ever produce a same-frame double sort
            // (`InputPlugin#sortDropZones`, `src/input/InputPlugin.js` around line 2910, reached
            // only via >=2 active drop zones) is structurally unreachable in this scene. So this
            // scene's design, chosen for cost-isolation reasons, also removes the only mechanism
            // that could have made this specific counter fail — the invariant holding here is
            // real evidence the coalescing mechanism works, not evidence against a hazard this
            // scene was never able to exercise in the first place.
            expect(run.results.depthSortPerFrame.min, `run ${i + 1}: depthSort min`).toBe(1);
            expect(run.results.depthSortPerFrame.max, `run ${i + 1}: depthSort max`).toBe(1);
            expect(run.results.depthSortPerFrame.mean, `run ${i + 1}: depthSort mean`).toBe(1);

            // Fix round 1 (b): pinned to the exact values nine independent runs (three of them
            // an external reviewer's own re-run) reproduced bit-for-bit — the simulation is
            // fully deterministic given the fixed PRNG seed and the frame-indexed (not
            // delta-time) movement model, so `drawnMean < total` alone (previously the only
            // check here) would still pass at 499/500 and catch nothing. Any change to the
            // projection, `cullBounds`, or the camera/follow path should turn this red.
            expect(run.results.culling.drawnMin, `run ${i + 1}: culling drawnMin`).toBe(23);
            expect(run.results.culling.drawnMax, `run ${i + 1}: culling drawnMax`).toBe(59);
            expect(run.results.culling.drawnMean, `run ${i + 1}: culling drawnMean`).toBeCloseTo(44.8, 4);
            expect(run.results.culling.total).toBe(DEFAULT_ENTITY_COUNT);

            // Fix round 1 (a), sensitivity corrected in fix round 2: the actual CI regression
            // gate, against a curated, committed baseline — NOT the 16.6ms/60fps aspirational
            // number (that comparison is printed below and recorded in the report, but
            // deliberately never asserted: a build that goes red because reality is slower than
            // an aspirational target would pressure someone into shrinking the scene, which this
            // task exists to refuse to do). What this gate actually catches, worked out from
            // this benchmark's own numbers (full derivation in bench-baseline.json's `_purpose`
            // and the report's fix-(a) section): roughly an 8-12x blowup in the
            // ENTITY-ATTRIBUTABLE portion of frameWorkTime (~0.15-0.20ms today). It is a
            // catastrophe-catcher, not a fine-grained regression detector — a 10x `place()`
            // slowdown or a broken depthSort coalescing (caught instead by the
            // depthSort===1 assertion above) would NOT trip it at today's numbers.
            expect(
                run.results.frameWorkTime.p95,
                `run ${i + 1}: frameWorkTime.p95 vs baseline ${baseline.frameWorkTimeP95Ms}ms x ${baseline.toleranceMultiplier}`
            ).toBeLessThan(baseline.frameWorkTimeP95Ms * baseline.toleranceMultiplier);
        }

        // --- The null-hypothesis control: the SAME page, SAME instrumentation, 0 entities. ---
        const controlRuns: Array<{ results: BenchResults; rendererInfo: string | null }> = [];

        for (let i = 0; i < RUNS; i += 1) {
            const run = await runOnce(page, 0);
            controlRuns.push(run);
            logRun(`0-entity control ${i + 1}/${RUNS}`, run);

            expect(run.results.entityCount).toBe(0);
            expect(run.results.culling.total).toBe(0);

            // With nothing ever calling setCell()/place(), setDepth() is never called, so
            // sortChildrenFlag is never raised — depthSort must read exactly 0, not 1. A
            // different invariant from the 500-entity scene, for the same architectural reason.
            expect(run.results.depthSortPerFrame.min, `control ${i + 1}: depthSort min`).toBe(0);
            expect(run.results.depthSortPerFrame.max, `control ${i + 1}: depthSort max`).toBe(0);
            expect(run.results.depthSortPerFrame.mean, `control ${i + 1}: depthSort mean`).toBe(0);
        }

        // --- The point of the control: prove framePeriod is a floor, frameWorkTime is not. ---
        for (const [i, run] of mainRuns.entries()) {
            const control = controlRuns[i];
            console.log(
                `[bench comparison ${i + 1}/${RUNS}] `
                + `framePeriod 500=${run.results.framePeriod.median.toFixed(3)}ms `
                + `0=${control.results.framePeriod.median.toFixed(3)}ms `
                + `(expected to be close — that is the floor) | `
                + `frameWorkTime 500=${run.results.frameWorkTime.mean.toFixed(3)}ms `
                + `0=${control.results.frameWorkTime.mean.toFixed(3)}ms `
                + `(expected to differ — that is the actual cost)`
            );

            // Fix round 2, Item 2: this was a console.log and nothing else — the "floor can
            // never again be read as a cost" rule shipped as a print statement, so a future
            // frameWorkTime that flatlined at the control's ~0.06-0.07ms regardless of entity
            // count would pass this whole suite. Now it can't: the entity-attributable signal
            // must clear the control by a real margin, not just print alongside it.
            expect(
                run.results.frameWorkTime.mean,
                `run ${i + 1}: frameWorkTime.mean (${run.results.frameWorkTime.mean}ms) must clear `
                + `the null-hypothesis control (${control.results.frameWorkTime.mean}ms) by at `
                + `least ${NULL_HYPOTHESIS_MULTIPLIER}x — if it doesn't, the entity-count signal `
                + 'has disappeared, which is exactly the failure fix round 1 exists to catch'
            ).toBeGreaterThan(control.results.frameWorkTime.mean * NULL_HYPOTHESIS_MULTIPLIER);

            const verdict = run.results.frameWorkTime.p95 < P95_THRESHOLD_MS ? 'PASS' : 'MISS';
            console.log(
                `[bench run ${i + 1}/${RUNS}] frameWorkTime.p95=${run.results.frameWorkTime.p95.toFixed(3)}ms `
                + `vs aspirational threshold=${P95_THRESHOLD_MS}ms: ${verdict} (informational only, not asserted)`
            );
        }

        fs.mkdirSync(ARTIFACTS, { recursive: true });
        fs.writeFileSync(
            path.join(ARTIFACTS, 'bench-results.json'),
            `${JSON.stringify({ defaultEntityCount: DEFAULT_ENTITY_COUNT, p95ThresholdMs: P95_THRESHOLD_MS, mainRuns, controlRuns }, null, 2)}\n`
        );
    });
});
